; CYD MiniTV ESP32-2432S028R

[env:cyd]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 115200
upload_protocol = custom
extra_scripts = post:scripts/custom_upload.py
board_build.partitions = huge_app.csv

lib_deps =
    https://github.com/moononournation/Arduino_GFX.git#v1.6.1
    https://github.com/bitbank2/JPEGDEC.git#1.8.2
    paulstoffregen/XPT2046_Touchscreen
    tzapu/WiFiManager@^2.0.17
    bblanchon/ArduinoJson@^7.2.1

build_flags =
    -O2
    -DCORE_DEBUG_LEVEL=1
